### ISSUE TITLE
Pseudo voight params bug

### ISSUE THREAD

**Issue by kernb2** [raman-noodles/Raman-noodles#15]
**Description**
Key Error involving the plot_components = True  when importing in experimental formic acid and spectrafitting it.

Plots an additional descriptor p16 when only fifteen descriptors are described

**To Reproduce**
1. Import experimental formic acid 
2. spectrafit.plot_fit(x_data, y_data, out, plot_components=True)
3.KeyError                                  Traceback (most recent call last)
<ipython-input-14-1e895b5b3b11> in <module>
----> 1 spectrafit.plot_fit(x_data, y_data, out, plot_components=True)

~\Anaconda3\lib\site-packages\ramannoodles-2.0b0-py3.6.egg\ramannoodles\spectrafit.py in plot_fit(x_data, y_data, fit_result, plot_components)
    274         for i in range(1, int(len(fit_result.values)/5)):
    275             prefix = 'p{}_'.format(i+1)
--> 276             plt.plot(x_data, comps[prefix], 'b--', linewidth=1)
    277     plt.legend(fontsize=12)
    278     plt.show()

KeyError: 'p16_'

**Expected behavior**
Runs fitting of the peaks without additional descriptors

**Comment by erasmuss** [comment]
is this completed now? @ParkerSteichen

**Comment by ParkerSteichen** [comment]
No it is not. I will take a look today. Sorry with Easter this weekend I was not able to look at anything.

**Comment by ParkerSteichen** [comment]
Quick and easy fix. The new model has 6 parameters instead of 5 so we just needed to change one number. I also updated the plot labels and added to the unit test so that it actually runs the function and will catch errors like this in the future. I didnt have it actually run the function previously since I was not clear how we could test the output of a plotting function.
